Feature/add maybe type
myparcelnl/ts-utils pull request #90
Opened 2023-05-12 08:18 UTC by zoeyfrisart

This pull request adds the Maybe type which is used in internal MyParcel applications.

Adding this to the ts-utils, since Remco asked for this type to be added to the TS-utils.

2023-05-17 09:05 UTC, Cysword approved these changes

2023-05-30 14:39 UTC, EdieLemoine requested changes

2023-05-30 14:39 UTC, EdieLemoine commented on src/types/maybe.ts
> +export type Maybe<T> = T | null | undefined;
missing newline

2023-05-30 14:48 UTC, zoeyfrisart commented on src/types/maybe.ts
> +export type Maybe<T> = T | null | undefined;
```suggestion
export type Maybe<T> = T | null | undefined;

```

2023-05-30 14:51 UTC, EdieLemoine approved these changes

2023-06-30 20:12 UTC, merged